#!/usr/bin/env bash
# Stage the app into docs/app/ so GitHub Pages can serve the whole site.
#
# docs/ is the website and is hand-written and committed; docs/app/ is a copy of
# the app and is generated by this script. Pages is pointed at "main branch,
# /docs folder", which then serves:
#
#   /       the landing page
#   /app/   the app itself
#
# The landing page's demo imports ../app/js/core.js — the real pixelation code,
# not a copy of it — so the site cannot show something the app does not do.
set -euo pipefail

cd "$(dirname "$0")"
./stage-app.sh docs/app

echo
echo "Site ready. Preview it with:"
echo "  python3 -m http.server -d docs 8000"
